site_name: Understand and Use Home Assistant Statistics

docs_dir: docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js
  - javascripts/mermaid.js

plugins:
  - search

nav:
  - Home: index.md
  - Statistics Documentation:
      - Overview: doc/overview.md
      - Part 1 - Foundational Concepts: doc/part1_fundamental_concepts.md
      - Part 2 - Statistics Generation: doc/part2_statistics_generation.md
      - Part 3 - Working with Statistics : doc/part3_working_with_statistics.md
      - Part 4 - Best Practices and Troubleshooting: doc/part4_practices_troubleshooting.md
      - Part 5 - Finding & Fixing Statistics Errors: doc/part5_find_fix.md
      - Appendix 1 - Units of Measurement: doc/apdx_1_set_units.md
      - Appendix 2 - Change Unit of Measurement: doc/apdx_2_change_units.md
      - Appendix 3 - Mysterious Table Fields: doc/apdx_3_stat_fields.md
      - Appendix 4 - Statistics domains: doc/apdx_4_stat_domains.md
      - Quick Reference Guide: doc/quick_reference_guide.md
      - Glossary: doc/glossary.md
  - SQL Examples:
      - Overview: sql/sql_overview.md
      - States: sql/sql_states.md
      - Statistics: sql/sql_statistics.md
      - Errors: sql/sql_errors.md
      - Tips: sql/sql_tips.md

markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
