site_name: Home Assistant Statistics Docs

docs_dir: docs

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Home: index.md
  - Statistics Documentation:
      - Overview: doc/overview.md
      - Part 1 - Foundational Concepts: doc/part1_fundamental_concepts.md
      - Part 2 - Statistics Generation: doc/part2_statistics_generation.md
      - Part 3 - Working with Statistics : doc/part3_working_with_statistics.md
      - Part 4 - Best Practices and Troubleshooting: doc/part4_practices_troubleshooting.md
  - SQL Examples:
      - Overview: sql/sql_overview.md
      - Statistics: sql/sql_stat.md
      - States: sql/sql_states.md
      - Tips: sql/sql_tips.md
      - Python: sql/sql_python.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
