site_name: Home Assistant Statistics Docs

docs_dir: docs

theme:
  name: material

nav:
  - Home: index.md
  - Documentation:
      - Overview: doc/ha_statistics.md
      - Part 1 - Foundational Concepts: doc/part1_fundamental_concepts.md
      - Part 2 - Statistics Generation: doc/part2_statistics_generation.md
      - Part 4 - Best Practices and Troubleshooting: doc/part4_practices_troubleshooting.md
      - Statistics Fields: doc/stat_fields.md
      - Non-sensor Examples: doc/statistics_not_sensor.md
  - SQL:
      - Python: sql/sql_python.md
      - Statistics: sql/sql_stat.md
      - States: sql/sql_states.md
      - Tips: sql/sql_tips.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
